# Generated by Django 5.1 on 2024-09-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='types',
            field=models.CharField(choices=[('R', 'Records'), ('C', 'Clothings'), ('P', 'Posters'), ('D', 'Divers')], default='', max_length=5),
            preserve_default=False,
        ),
    ]
